# production:
#   url: redis://redis.example.com:6379

local: &local
  adapter: redis
  url: redis://localhost:6379
  channel_prefix: cable_test_production

development: *local
test: *local
production:
  <<: *local
  password: <%= Rails.application.secrets.redis_password %>

