# production:
#   url: redis://redis.example.com:6379

local: &local
  adapter: redis
  url: redis://localhost:6379

development:
  <<: *local
  channel_prefix: cable_test_development

test:
  <<: *local
  channel_prefix: cable_test_test

production:
  <<: *local
  password: <%= Rails.application.secrets.redis_password %>
  channel_prefix: cable_test_production

